---
version: '3.9'
services:
  grafana:
    image: grafana/grafana:8.1.1
    volumes:
      - ./dist:/var/lib/grafana/plugins/pyroscope-datasource
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=pyroscope-datasource
      - GF_INSTALL_PLUGINS=pyroscope-panel
    ports:
      - 3000:3000

  pyroscope:
    image:
      'pyroscope/pyroscope:latest'
    ports:
    - 4040:4040
    command:
      - server
    environment:
      - PYROSCOPE_LOG_LEVEL=info
